### ISSUE TITLE
Staging: zoomed-in pic goes out of the phone screen, which needs manual adjustment.

### ISSUE THREAD

**Issue by Kateliuxue** [initiumlab/initiumlab.com#83] opened 2015-09-22 06:54 UTC
![img_1083](https://cloud.githubusercontent.com/assets/14042060/10012345/c55c7906-6139-11e5-8e99-4b509c3b333b.PNG)
 iphone 5s  ios 8.1

**Comment by andyshuxin** [comment] 2015-09-23 11:50
@Kateliuxue Can't reproduce the problem on my devices? Can you still see this problem on yours?

**Comment by andyshuxin** [comment] 2015-09-23 12:57
This is iOS8-specific problem.

**Comment by frankinit** [comment] 2015-09-24 07:17
On iOS 9, Safari auto adjusts the width, but it causes a flash.

**Comment by andyshuxin** [comment] 2015-09-24 08:52
@frankinit @Kateliuxue 
Fixed with https://github.com/initiumlab/hexo-theme-next/commit/d49c653b481054317e7763242b2c4747d55824c2.

**Comment by Kateliuxue** [comment] 2015-09-24 09:40
But the zoomed-in picture becomes even much smaller.

**Comment by andyshuxin** [comment] 2015-09-24 09:47
@Kateliuxue Indeed. Probably should disable lightbox altogether on smaller screens. Please close this issue (which is solved) and open another issue, labelled `enhancement`, about that idea.
cc @yyfjmb @hupili

**Closed** 2015-09-24 09:52 UTC
Labels: bug
